project:
  crs: "EPSG:4326"
  target_resolution_deg: 0.05

paths:
  data_root: "c:/dust-mvp/data"
  raw_dir: "c:/dust-mvp/data/raw"
  derived_dir: "c:/dust-mvp/data/derived"
  admin_dir: "c:/dust-mvp/data/admin"
  provinces_shp: "c:/dust-mvp/data/admin/turkiye_provinces.shp"

apis:
  laads:
    token: "eyJ0eXAiOiJKV1QiLCJvcmlnaW4iOiJFYXJ0aGRhdGEgTG9naW4iLCJzaWciOiJlZGxqd3RwdWJrZXlfb3BzIiwiYWxnIjoiUlMyNTYifQ.eyJ0eXBlIjoiVXNlciIsInVpZCI6ImVzcmFvbmN1MSIsImV4cCI6MTc2NDExNTE5OSwiaWF0IjoxNzU4ODkwNTA4LCJpc3MiOiJodHRwczovL3Vycy5lYXJ0aGRhdGEubmFzYS5nb3YiLCJpZGVudGl0eV9wcm92aWRlciI6ImVkbF9vcHMiLCJhY3IiOiJlZGwiLCJhc3N1cmFuY2VfbGV2ZWwiOjN9.3WLiqkdqkjrlmWJS2mBIof02BsZRQt3HEgsdTBCzHHoeaYaW5jGmZ40pl8C5exD52V2E2I2LxBbSgOU7I4jOAfwDkSmrFr8YbKVROm_20fiE7GaxxueV9KvP3fBtQeL_BO_dFkjrLIf18rC5Hm3YVsK5JFnDJzXFOAYlVG6vqcKzeeB9DUzYCZF8eO5rUavR8CDRFYyTCMRw-N5nlGzYvZQUIEEuLXdBX5-iyvu0WmaZ0-9UdpnOJefP-xmIbqmZTBl-CS4vFpeozUvulrR7Dqu9LJiy7SgTk33Xj0XpoaNL66O1QDbJW3RgtlX_dFNZFmvoGnYDKA1cBzbU09o1tQ"
  cams:
    key: "c46f9bcc-6720-4d14-aea5-0eebd4b700a9"

model:
  pm25_regression:
    # Enhanced PM2.5 model: PM2.5 = a0 + a1*AOD + a2*RH + a3*BLH + a4*DustAOD + a5*DustAOD*RH + a6*DustAOD*BLH
    a0: 8.0      # Intercept (background PM2.5)
    a1: 25.0     # AOD coefficient 
    a2: 0.08     # RH coefficient (hygroscopic growth)
    a3: -0.012   # BLH coefficient (dilution effect)
    a4: 15.0     # Dust AOD coefficient
    a5: 0.1      # Dust-RH interaction
    a6: -0.005   # Dust-BLH interaction

runtime:
  threads: 4
  write_cog: true

# Email service configuration
email:
  smtp_server: "${SMTP_SERVER}"
  smtp_port: 587
  smtp_username: "${SMTP_USERNAME}"
  smtp_password: "${SMTP_PASSWORD}"
  from_email: "${FROM_EMAIL}"
  from_name: "Türkiye Toz Uyarı Sistemi"
  use_tls: true

# Scheduler configuration
scheduler:
  daily_run_time: "06:00"  # UTC time
  pipeline_timeout_minutes: 60
  max_retries: 3
  retry_delay_minutes: 15
  alert_processing_interval_minutes: 10
  cleanup_old_data_days: 90

# Web application settings
webapp:
  website_url: "${WEBSITE_URL}"
  api_url: "${API_URL}"
  enable_cors: true
  cors_origins: ["http://localhost:3000", "https://dustalert.tr"]

# Database configuration
database:
  url: "${DATABASE_URL}"

